apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nest-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: nguyenlyminhman/nestjs-app:1.0.0
          ports:
            - containerPort: 3001
